### ISSUE TITLE
[Vulnerability][Critical] A1 - SQL Injection

### ISSUE THREAD

**Issue by brunocascio** [zegnhabi/AT#1]
Se encontró una vulnerabilidad del tipo [SQL Injection](https://www.owasp.org/index.php/Top_10_2017-A1-Injection) al insertar una terminal https://github.com/zegnhabi/AT/blob/master/insertar_terminal.php

El error tambien se repite para las mayorias de las consultas.

Script para explotar la vulnerabilidad:

```
sqlmap --wizard --url http://<server.com>/insertar_terminal.php -p terminal

POST DATA: terminal=--&rand=0.8832366507097014
```

Se recomienda utilizar [prepared statements](http://php.net/manual/en/mysqli.quickstart.prepared-statements.php) para realizar las consultas y asi evitar caracteres que puedan afectar la integridad/confidencialidad de la base de datos.

**Comment by maitret** [comment]
Buen aporte @brunocascio , se que @zegnhabi en breve lo estará corrigiendo ;)

**Comment by zegnhabi** [comment]
se cambió la conexión para usar la extensión mysqli. :)
